[workspace]
members = [
    "picobroker-core",
    "picobroker-tokio",
    "picobroker-embassy",
    "examples/tokio_server",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
