[package]
name = "tokio_mqtt_server"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
picobroker-tokio = { path = "../../../picobroker-tokio" }
tokio = { version = "1", features = ["net", "time", "macros", "rt-multi-thread", "io-util", "sync"] }
log = "0.4"
env_logger = "0.11"
