[package]
name = "tokio_mqtt_client"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
picobroker = { path = "../../" }
tokio = { version = "1", features = ["net", "time", "macros", "rt-multi-thread", "io-util"] }
log = "0.4"
env_logger = "0.11"
bytes = "1"
