[package]
name = "picobroker-tokio"
version.workspace = true
edition.workspace = true

[dependencies]
picobroker-core = { path = "../picobroker-core" }
async-trait = "0.1"
tokio = { version = "1", features = ["net", "time", "macros", "rt-multi-thread", "io-util"] }
