[package]
name = "tokio_server"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
picobroker-tokio = { path = "../../picobroker-tokio" }
tokio = { version = "1", features = ["full"] }
env_logger = "0.11"
